// Generated by `npm run db:types` — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "agent_location_events": {
                  Row: {
                    "accuracy_meters": number | null,"agent_id": string,"device_id": string | null,"id": string,"latitude": number,"longitude": number,"recorded_at": string,"task_id": string | null
                  }
                  Insert: {
                    "accuracy_meters"?: number | null,"agent_id": string,"device_id"?: string | null,"id"?: string,"latitude": number,"longitude": number,"recorded_at"?: string,"task_id"?: string | null
                  }
                  Update: {
                    "accuracy_meters"?: number | null,"agent_id"?: string,"device_id"?: string | null,"id"?: string,"latitude"?: number,"longitude"?: number,"recorded_at"?: string,"task_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "agent_location_events_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_location_events_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_location_events_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_location_events_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "agent_location_events_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_location_events_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_location_events_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"agents": {
                  Row: {
                    "created_at": string,"employee_code": string | null,"id": string,"is_active": boolean,"profile_id": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"employee_code"?: string | null,"id"?: string,"is_active"?: boolean,"profile_id": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"employee_code"?: string | null,"id"?: string,"is_active"?: boolean,"profile_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "agents_profile_id_fkey"
      columns: ["profile_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_feedback": {
                  Row: {
                    "created_at": string,"id": string,"notes": string | null,"prediction_id": string,"rating": string,"user_id": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"notes"?: string | null,"prediction_id": string,"rating": string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"notes"?: string | null,"prediction_id"?: string,"rating"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_feedback_prediction_id_fkey"
      columns: ["prediction_id"]
isOneToOne: false
      referencedRelation: "ai_current_predictions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "ai_feedback_prediction_id_fkey"
      columns: ["prediction_id"]
isOneToOne: false
      referencedRelation: "ai_predictions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "ai_feedback_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_models": {
                  Row: {
                    "created_at": string,"description": string,"feature_version": string,"id": string,"model_type": string,"name": string,"status": string,"version": string
                  }
                  Insert: {
                    "created_at"?: string,"description": string,"feature_version": string,"id"?: string,"model_type": string,"name": string,"status"?: string,"version": string
                  }
                  Update: {
                    "created_at"?: string,"description"?: string,"feature_version"?: string,"id"?: string,"model_type"?: string,"name"?: string,"status"?: string,"version"?: string
                  }
                  Relationships: [
                    
                  ]
                },"ai_predictions": {
                  Row: {
                    "confidence": number | null,"created_at": string,"entity_id": string,"entity_type": string,"evaluated_at": string | null,"expires_at": string | null,"explanation": NonNullable<Json>,"feature_version": string,"fingerprint": string,"generated_at": string,"id": string,"model_name": string,"model_version": string,"outcome": Json | null,"prediction_type": string,"prediction_value": NonNullable<Json>
                  }
                  Insert: {
                    "confidence"?: number | null,"created_at"?: string,"entity_id": string,"entity_type": string,"evaluated_at"?: string | null,"expires_at"?: string | null,"explanation"?: NonNullable<Json>,"feature_version": string,"fingerprint": string,"generated_at"?: string,"id"?: string,"model_name": string,"model_version": string,"outcome"?: Json | null,"prediction_type": string,"prediction_value": NonNullable<Json>
                  }
                  Update: {
                    "confidence"?: number | null,"created_at"?: string,"entity_id"?: string,"entity_type"?: string,"evaluated_at"?: string | null,"expires_at"?: string | null,"explanation"?: NonNullable<Json>,"feature_version"?: string,"fingerprint"?: string,"generated_at"?: string,"id"?: string,"model_name"?: string,"model_version"?: string,"outcome"?: Json | null,"prediction_type"?: string,"prediction_value"?: NonNullable<Json>
                  }
                  Relationships: [
                    
                  ]
                },"ai_recommendations": {
                  Row: {
                    "confidence": number | null,"created_at": string,"dedupe_key": string,"description": string,"entity_id": string | null,"entity_type": string,"id": string,"model_name": string,"model_version": string,"reasoning": NonNullable<Json>,"recommendation_type": string,"review_notes": string | null,"reviewed_at": string | null,"reviewed_by": string | null,"status": string,"title": string
                  }
                  Insert: {
                    "confidence"?: number | null,"created_at"?: string,"dedupe_key": string,"description": string,"entity_id"?: string | null,"entity_type": string,"id"?: string,"model_name": string,"model_version": string,"reasoning"?: NonNullable<Json>,"recommendation_type": string,"review_notes"?: string | null,"reviewed_at"?: string | null,"reviewed_by"?: string | null,"status"?: string,"title": string
                  }
                  Update: {
                    "confidence"?: number | null,"created_at"?: string,"dedupe_key"?: string,"description"?: string,"entity_id"?: string | null,"entity_type"?: string,"id"?: string,"model_name"?: string,"model_version"?: string,"reasoning"?: NonNullable<Json>,"recommendation_type"?: string,"review_notes"?: string | null,"reviewed_at"?: string | null,"reviewed_by"?: string | null,"status"?: string,"title"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_recommendations_reviewed_by_fkey"
      columns: ["reviewed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_runs": {
                  Row: {
                    "duration_ms": number | null,"error": string | null,"finished_at": string | null,"id": string,"input_tokens": number | null,"insufficient": number,"kind": string,"model": string | null,"output_tokens": number | null,"predictions": number,"provider": string | null,"recommendations": number,"started_at": string,"started_by": string | null,"status": string,"trigger": string
                  }
                  Insert: {
                    "duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"input_tokens"?: number | null,"insufficient"?: number,"kind": string,"model"?: string | null,"output_tokens"?: number | null,"predictions"?: number,"provider"?: string | null,"recommendations"?: number,"started_at"?: string,"started_by"?: string | null,"status"?: string,"trigger": string
                  }
                  Update: {
                    "duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"input_tokens"?: number | null,"insufficient"?: number,"kind"?: string,"model"?: string | null,"output_tokens"?: number | null,"predictions"?: number,"provider"?: string | null,"recommendations"?: number,"started_at"?: string,"started_by"?: string | null,"status"?: string,"trigger"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_runs_started_by_fkey"
      columns: ["started_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_settings": {
                  Row: {
                    "description": string,"enabled": boolean,"key": string,"updated_at": string,"updated_by": string | null
                  }
                  Insert: {
                    "description": string,"enabled"?: boolean,"key": string,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Update: {
                    "description"?: string,"enabled"?: boolean,"key"?: string,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_settings_updated_by_fkey"
      columns: ["updated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_summaries": {
                  Row: {
                    "content": NonNullable<Json>,"facts": NonNullable<Json>,"generated_at": string,"generated_by": string | null,"id": string,"model": string | null,"period": string,"provider": string
                  }
                  Insert: {
                    "content": NonNullable<Json>,"facts": NonNullable<Json>,"generated_at"?: string,"generated_by"?: string | null,"id"?: string,"model"?: string | null,"period": string,"provider": string
                  }
                  Update: {
                    "content"?: NonNullable<Json>,"facts"?: NonNullable<Json>,"generated_at"?: string,"generated_by"?: string | null,"id"?: string,"model"?: string | null,"period"?: string,"provider"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_summaries_generated_by_fkey"
      columns: ["generated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"app_settings": {
                  Row: {
                    "description": string,"key": string,"updated_at": string,"value": number
                  }
                  Insert: {
                    "description": string,"key": string,"updated_at"?: string,"value": number
                  }
                  Update: {
                    "description"?: string,"key"?: string,"updated_at"?: string,"value"?: number
                  }
                  Relationships: [
                    
                  ]
                },"audit_logs": {
                  Row: {
                    "action": string,"actor_user_id": string | null,"created_at": string,"entity_id": string | null,"entity_type": string,"id": string,"new_values": Json | null,"old_values": Json | null
                  }
                  Insert: {
                    "action": string,"actor_user_id"?: string | null,"created_at"?: string,"entity_id"?: string | null,"entity_type": string,"id"?: string,"new_values"?: Json | null,"old_values"?: Json | null
                  }
                  Update: {
                    "action"?: string,"actor_user_id"?: string | null,"created_at"?: string,"entity_id"?: string | null,"entity_type"?: string,"id"?: string,"new_values"?: Json | null,"old_values"?: Json | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "audit_logs_actor_user_id_fkey"
      columns: ["actor_user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"cash_collections": {
                  Row: {
                    "agent_id": string,"collected_amount": number,"collected_at": string | null,"collection_reference": string | null,"created_at": string,"currency": string,"expected_amount": number,"id": string,"notes": string | null,"payment_method": string | null,"task_id": string,"updated_at": string
                  }
                  Insert: {
                    "agent_id": string,"collected_amount"?: number,"collected_at"?: string | null,"collection_reference"?: string | null,"created_at"?: string,"currency"?: string,"expected_amount": number,"id"?: string,"notes"?: string | null,"payment_method"?: string | null,"task_id": string,"updated_at"?: string
                  }
                  Update: {
                    "agent_id"?: string,"collected_amount"?: number,"collected_at"?: string | null,"collection_reference"?: string | null,"created_at"?: string,"currency"?: string,"expected_amount"?: number,"id"?: string,"notes"?: string | null,"payment_method"?: string | null,"task_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "cash_collections_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "cash_collections_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "cash_collections_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "cash_collections_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "cash_collections_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "cash_collections_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "cash_collections_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"checkins": {
                  Row: {
                    "accuracy_meters": number | null,"agent_id": string,"checked_in_at": string,"device_id": string | null,"distance_from_location_meters": number | null,"geofence_radius_meters": number | null,"id": string,"is_within_geofence": boolean,"latitude": number,"longitude": number,"notes": string | null,"task_id": string
                  }
                  Insert: {
                    "accuracy_meters"?: number | null,"agent_id": string,"checked_in_at"?: string,"device_id"?: string | null,"distance_from_location_meters"?: number | null,"geofence_radius_meters"?: number | null,"id"?: string,"is_within_geofence": boolean,"latitude": number,"longitude": number,"notes"?: string | null,"task_id": string
                  }
                  Update: {
                    "accuracy_meters"?: number | null,"agent_id"?: string,"checked_in_at"?: string,"device_id"?: string | null,"distance_from_location_meters"?: number | null,"geofence_radius_meters"?: number | null,"id"?: string,"is_within_geofence"?: boolean,"latitude"?: number,"longitude"?: number,"notes"?: string | null,"task_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "checkins_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "checkins_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "checkins_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "checkins_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "checkins_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "checkins_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "checkins_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"communication_queue": {
                  Row: {
                    "attempt_count": number,"channel": string,"created_at": string,"failed_at": string | null,"id": string,"last_error": string | null,"message": string,"notification_id": string | null,"payload": NonNullable<Json>,"provider": string | null,"provider_message_id": string | null,"recipient_address": string,"recipient_user_id": string | null,"scheduled_at": string,"sent_at": string | null,"status": string,"subject": string | null,"updated_at": string
                  }
                  Insert: {
                    "attempt_count"?: number,"channel": string,"created_at"?: string,"failed_at"?: string | null,"id"?: string,"last_error"?: string | null,"message": string,"notification_id"?: string | null,"payload"?: NonNullable<Json>,"provider"?: string | null,"provider_message_id"?: string | null,"recipient_address": string,"recipient_user_id"?: string | null,"scheduled_at"?: string,"sent_at"?: string | null,"status"?: string,"subject"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "attempt_count"?: number,"channel"?: string,"created_at"?: string,"failed_at"?: string | null,"id"?: string,"last_error"?: string | null,"message"?: string,"notification_id"?: string | null,"payload"?: NonNullable<Json>,"provider"?: string | null,"provider_message_id"?: string | null,"recipient_address"?: string,"recipient_user_id"?: string | null,"scheduled_at"?: string,"sent_at"?: string | null,"status"?: string,"subject"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "communication_queue_notification_id_fkey"
      columns: ["notification_id"]
isOneToOne: false
      referencedRelation: "notifications"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "communication_queue_recipient_user_id_fkey"
      columns: ["recipient_user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"customers": {
                  Row: {
                    "address_line1": string | null,"address_line2": string | null,"city": string | null,"country": string,"created_at": string,"customer_code": string | null,"email": string | null,"id": string,"is_active": boolean,"name": string,"phone": string | null,"postal_code": string | null,"state": string | null,"updated_at": string
                  }
                  Insert: {
                    "address_line1"?: string | null,"address_line2"?: string | null,"city"?: string | null,"country"?: string,"created_at"?: string,"customer_code"?: string | null,"email"?: string | null,"id"?: string,"is_active"?: boolean,"name": string,"phone"?: string | null,"postal_code"?: string | null,"state"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "address_line1"?: string | null,"address_line2"?: string | null,"city"?: string | null,"country"?: string,"created_at"?: string,"customer_code"?: string | null,"email"?: string | null,"id"?: string,"is_active"?: boolean,"name"?: string,"phone"?: string | null,"postal_code"?: string | null,"state"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"locations": {
                  Row: {
                    "address_line1": string | null,"address_line2": string | null,"city": string | null,"contact_person": string | null,"contact_phone": string | null,"country": string,"created_at": string,"customer_id": string,"geofence_radius_meters": number,"id": string,"is_active": boolean,"latitude": number | null,"location_name": string,"longitude": number | null,"postal_code": string | null,"state": string | null,"updated_at": string
                  }
                  Insert: {
                    "address_line1"?: string | null,"address_line2"?: string | null,"city"?: string | null,"contact_person"?: string | null,"contact_phone"?: string | null,"country"?: string,"created_at"?: string,"customer_id": string,"geofence_radius_meters"?: number,"id"?: string,"is_active"?: boolean,"latitude"?: number | null,"location_name": string,"longitude"?: number | null,"postal_code"?: string | null,"state"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "address_line1"?: string | null,"address_line2"?: string | null,"city"?: string | null,"contact_person"?: string | null,"contact_phone"?: string | null,"country"?: string,"created_at"?: string,"customer_id"?: string,"geofence_radius_meters"?: number,"id"?: string,"is_active"?: boolean,"latitude"?: number | null,"location_name"?: string,"longitude"?: number | null,"postal_code"?: string | null,"state"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "locations_customer_id_fkey"
      columns: ["customer_id"]
isOneToOne: false
      referencedRelation: "customers"
      referencedColumns: ["id"]
    }
                  ]
                },"notification_preferences": {
                  Row: {
                    "cash_collection": boolean,"created_at": string,"email_enabled": boolean,"id": string,"proof_upload": boolean,"sms_enabled": boolean,"task_assignment": boolean,"task_reminder": boolean,"task_status": boolean,"updated_at": string,"user_id": string,"whatsapp_enabled": boolean
                  }
                  Insert: {
                    "cash_collection"?: boolean,"created_at"?: string,"email_enabled"?: boolean,"id"?: string,"proof_upload"?: boolean,"sms_enabled"?: boolean,"task_assignment"?: boolean,"task_reminder"?: boolean,"task_status"?: boolean,"updated_at"?: string,"user_id": string,"whatsapp_enabled"?: boolean
                  }
                  Update: {
                    "cash_collection"?: boolean,"created_at"?: string,"email_enabled"?: boolean,"id"?: string,"proof_upload"?: boolean,"sms_enabled"?: boolean,"task_assignment"?: boolean,"task_reminder"?: boolean,"task_status"?: boolean,"updated_at"?: string,"user_id"?: string,"whatsapp_enabled"?: boolean
                  }
                  Relationships: [
                    {
      foreignKeyName: "notification_preferences_user_id_fkey"
      columns: ["user_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"notifications": {
                  Row: {
                    "created_at": string,"data": NonNullable<Json>,"dedupe_key": string,"id": string,"is_read": boolean,"message": string,"read_at": string | null,"recipient_user_id": string,"task_id": string | null,"title": string,"type": string
                  }
                  Insert: {
                    "created_at"?: string,"data"?: NonNullable<Json>,"dedupe_key": string,"id"?: string,"is_read"?: boolean,"message": string,"read_at"?: string | null,"recipient_user_id": string,"task_id"?: string | null,"title": string,"type": string
                  }
                  Update: {
                    "created_at"?: string,"data"?: NonNullable<Json>,"dedupe_key"?: string,"id"?: string,"is_read"?: boolean,"message"?: string,"read_at"?: string | null,"recipient_user_id"?: string,"task_id"?: string | null,"title"?: string,"type"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "notifications_recipient_user_id_fkey"
      columns: ["recipient_user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "notifications_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "notifications_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "notifications_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "notifications_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"products": {
                  Row: {
                    "created_at": string,"description": string | null,"id": string,"is_active": boolean,"price": number | null,"product_name": string,"sku": string,"unit": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"description"?: string | null,"id"?: string,"is_active"?: boolean,"price"?: number | null,"product_name": string,"sku": string,"unit"?: string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"description"?: string | null,"id"?: string,"is_active"?: boolean,"price"?: number | null,"product_name"?: string,"sku"?: string,"unit"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"profiles": {
                  Row: {
                    "created_at": string,"email": string,"full_name": string | null,"id": string,"is_active": boolean,"phone": string | null,"role": Database["public"]['Enums']["user_role"],"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"email": string,"full_name"?: string | null,"id": string,"is_active"?: boolean,"phone"?: string | null,"role"?: Database["public"]['Enums']["user_role"],"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"email"?: string,"full_name"?: string | null,"id"?: string,"is_active"?: boolean,"phone"?: string | null,"role"?: Database["public"]['Enums']["user_role"],"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"task_products": {
                  Row: {
                    "assigned_quantity": number,"created_at": string,"delivered_quantity": number,"delivery_notes": string | null,"id": string,"notes": string | null,"product_id": string,"task_id": string,"unit_price": number | null,"updated_at": string
                  }
                  Insert: {
                    "assigned_quantity": number,"created_at"?: string,"delivered_quantity"?: number,"delivery_notes"?: string | null,"id"?: string,"notes"?: string | null,"product_id": string,"task_id": string,"unit_price"?: number | null,"updated_at"?: string
                  }
                  Update: {
                    "assigned_quantity"?: number,"created_at"?: string,"delivered_quantity"?: number,"delivery_notes"?: string | null,"id"?: string,"notes"?: string | null,"product_id"?: string,"task_id"?: string,"unit_price"?: number | null,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "task_products_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_products_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "task_products_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_products_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_products_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"task_proofs": {
                  Row: {
                    "agent_id": string,"created_at": string,"description": string | null,"file_name": string | null,"file_size_bytes": number | null,"id": string,"mime_type": string | null,"proof_type": string,"sha256": string | null,"storage_path": string | null,"task_id": string
                  }
                  Insert: {
                    "agent_id": string,"created_at"?: string,"description"?: string | null,"file_name"?: string | null,"file_size_bytes"?: number | null,"id"?: string,"mime_type"?: string | null,"proof_type": string,"sha256"?: string | null,"storage_path"?: string | null,"task_id": string
                  }
                  Update: {
                    "agent_id"?: string,"created_at"?: string,"description"?: string | null,"file_name"?: string | null,"file_size_bytes"?: number | null,"id"?: string,"mime_type"?: string | null,"proof_type"?: string,"sha256"?: string | null,"storage_path"?: string | null,"task_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "task_proofs_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_proofs_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_proofs_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_proofs_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "task_proofs_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_proofs_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_proofs_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"task_status_history": {
                  Row: {
                    "changed_at": string,"changed_by": string | null,"id": string,"new_status": Database["public"]['Enums']["task_status"],"notes": string | null,"old_status": Database["public"]['Enums']["task_status"] | null,"reason": string | null,"task_id": string
                  }
                  Insert: {
                    "changed_at"?: string,"changed_by"?: string | null,"id"?: string,"new_status": Database["public"]['Enums']["task_status"],"notes"?: string | null,"old_status"?: Database["public"]['Enums']["task_status"] | null,"reason"?: string | null,"task_id": string
                  }
                  Update: {
                    "changed_at"?: string,"changed_by"?: string | null,"id"?: string,"new_status"?: Database["public"]['Enums']["task_status"],"notes"?: string | null,"old_status"?: Database["public"]['Enums']["task_status"] | null,"reason"?: string | null,"task_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "task_status_history_changed_by_fkey"
      columns: ["changed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_status_history_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["current_task_id"]
    },{
      foreignKeyName: "task_status_history_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_status_history_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "task_monitor"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "task_status_history_task_id_fkey"
      columns: ["task_id"]
isOneToOne: false
      referencedRelation: "tasks"
      referencedColumns: ["id"]
    }
                  ]
                },"tasks": {
                  Row: {
                    "accepted_at": string | null,"agent_id": string | null,"assigned_at": string | null,"cancellation_reason": string | null,"completed_at": string | null,"completion_notes": string | null,"created_at": string,"created_by": string | null,"customer_id": string,"description": string | null,"expected_amount": number | null,"failure_reason": string | null,"id": string,"location_id": string,"priority": number,"scheduled_date": string | null,"scheduled_end_time": string | null,"scheduled_start_time": string | null,"started_at": string | null,"status": Database["public"]['Enums']["task_status"],"task_code": string,"task_type": Database["public"]['Enums']["task_type"],"title": string,"updated_at": string,"verified_at": string | null,"verified_by": string | null
                  }
                  Insert: {
                    "accepted_at"?: string | null,"agent_id"?: string | null,"assigned_at"?: string | null,"cancellation_reason"?: string | null,"completed_at"?: string | null,"completion_notes"?: string | null,"created_at"?: string,"created_by"?: string | null,"customer_id": string,"description"?: string | null,"expected_amount"?: number | null,"failure_reason"?: string | null,"id"?: string,"location_id": string,"priority"?: number,"scheduled_date"?: string | null,"scheduled_end_time"?: string | null,"scheduled_start_time"?: string | null,"started_at"?: string | null,"status"?: Database["public"]['Enums']["task_status"],"task_code"?: string,"task_type": Database["public"]['Enums']["task_type"],"title": string,"updated_at"?: string,"verified_at"?: string | null,"verified_by"?: string | null
                  }
                  Update: {
                    "accepted_at"?: string | null,"agent_id"?: string | null,"assigned_at"?: string | null,"cancellation_reason"?: string | null,"completed_at"?: string | null,"completion_notes"?: string | null,"created_at"?: string,"created_by"?: string | null,"customer_id"?: string,"description"?: string | null,"expected_amount"?: number | null,"failure_reason"?: string | null,"id"?: string,"location_id"?: string,"priority"?: number,"scheduled_date"?: string | null,"scheduled_end_time"?: string | null,"scheduled_start_time"?: string | null,"started_at"?: string | null,"status"?: Database["public"]['Enums']["task_status"],"task_code"?: string,"task_type"?: Database["public"]['Enums']["task_type"],"title"?: string,"updated_at"?: string,"verified_at"?: string | null,"verified_by"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_customer_id_fkey"
      columns: ["customer_id"]
isOneToOne: false
      referencedRelation: "customers"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "location_directory"
      referencedColumns: ["id","customer_id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "locations"
      referencedColumns: ["id","customer_id"]
    },{
      foreignKeyName: "tasks_verified_by_fkey"
      columns: ["verified_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            "agent_activity": {
                  Row: {
                    "account_active": boolean | null,"current_task_code": string | null,"current_task_id": string | null,"current_task_status": Database["public"]['Enums']["task_status"] | null,"current_task_type": Database["public"]['Enums']["task_type"] | null,"employee_code": string | null,"full_name": string | null,"id": string | null,"is_active": boolean | null,"last_completed_at": string | null,"last_location_at": string | null,"open_tasks": number | null
                  }
                  Relationships: [
                    
                  ]
                },"agent_directory": {
                  Row: {
                    "account_active": boolean | null,"created_at": string | null,"email": string | null,"employee_code": string | null,"full_name": string | null,"id": string | null,"is_active": boolean | null,"phone": string | null,"profile_id": string | null,"updated_at": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "agents_profile_id_fkey"
      columns: ["profile_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_current_predictions": {
                  Row: {
                    "confidence": number | null,"entity_id": string | null,"entity_type": string | null,"expires_at": string | null,"explanation": Json | null,"feature_version": string | null,"generated_at": string | null,"id": string | null,"is_stale": boolean | null,"model_name": string | null,"model_version": string | null,"outcome": Json | null,"prediction_type": string | null,"prediction_value": Json | null
                  }
                  Relationships: [
                    
                  ]
                },"ai_evaluation": {
                  Row: {
                    "eta_evaluated": number | null,"eta_mean_abs_error_minutes": number | null,"evaluated": number | null,"failed_total": number | null,"high_and_failed": number | null,"high_and_late": number | null,"high_not_late": number | null,"model_name": string | null,"model_version": string | null,"not_high_but_late": number | null,"not_high_not_late": number | null,"prediction_type": string | null,"predictions": number | null
                  }
                  Relationships: [
                    
                  ]
                },"communication_log": {
                  Row: {
                    "attempt_count": number | null,"channel": string | null,"created_at": string | null,"failed_at": string | null,"id": string | null,"last_error": string | null,"notification_id": string | null,"provider": string | null,"queue_id": string | null,"recipient_address": string | null,"recipient_name": string | null,"recipient_user_id": string | null,"sent_at": string | null,"status": string | null,"task_code": string | null,"task_id": string | null,"title": string | null,"type": string | null
                  }
                  Relationships: [
                    
                  ]
                },"location_directory": {
                  Row: {
                    "address_line1": string | null,"address_line2": string | null,"city": string | null,"contact_person": string | null,"contact_phone": string | null,"country": string | null,"created_at": string | null,"customer_active": boolean | null,"customer_code": string | null,"customer_id": string | null,"customer_name": string | null,"geofence_radius_meters": number | null,"id": string | null,"is_active": boolean | null,"latitude": number | null,"location_name": string | null,"longitude": number | null,"postal_code": string | null,"state": string | null,"updated_at": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "locations_customer_id_fkey"
      columns: ["customer_id"]
isOneToOne: false
      referencedRelation: "customers"
      referencedColumns: ["id"]
    }
                  ]
                },"task_directory": {
                  Row: {
                    "agent_id": string | null,"agent_name": string | null,"assigned_at": string | null,"created_at": string | null,"customer_code": string | null,"customer_id": string | null,"customer_name": string | null,"employee_code": string | null,"id": string | null,"location_city": string | null,"location_id": string | null,"location_name": string | null,"priority": number | null,"scheduled_date": string | null,"scheduled_end_time": string | null,"scheduled_start_time": string | null,"status": Database["public"]['Enums']["task_status"] | null,"task_code": string | null,"task_type": Database["public"]['Enums']["task_type"] | null,"title": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_customer_id_fkey"
      columns: ["customer_id"]
isOneToOne: false
      referencedRelation: "customers"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "location_directory"
      referencedColumns: ["id","customer_id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "locations"
      referencedColumns: ["id","customer_id"]
    }
                  ]
                },"task_monitor": {
                  Row: {
                    "agent_id": string | null,"agent_name": string | null,"assigned_total": number | null,"checked_in_at": string | null,"collected_amount": number | null,"created_at": string | null,"customer_code": string | null,"customer_id": string | null,"customer_name": string | null,"delivered_total": number | null,"employee_code": string | null,"expected_amount": number | null,"id": string | null,"last_accuracy_meters": number | null,"last_latitude": number | null,"last_location_at": string | null,"last_longitude": number | null,"line_count": number | null,"location_city": string | null,"location_id": string | null,"location_name": string | null,"priority": number | null,"proof_count": number | null,"scheduled_date": string | null,"scheduled_end_time": string | null,"scheduled_start_time": string | null,"status": Database["public"]['Enums']["task_status"] | null,"task_code": string | null,"task_type": Database["public"]['Enums']["task_type"] | null,"title": string | null,"updated_at": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_activity"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agent_directory"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_agent_id_fkey"
      columns: ["agent_id"]
isOneToOne: false
      referencedRelation: "agents"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_customer_id_fkey"
      columns: ["customer_id"]
isOneToOne: false
      referencedRelation: "customers"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "location_directory"
      referencedColumns: ["id","customer_id"]
    },{
      foreignKeyName: "tasks_location_belongs_to_customer"
      columns: ["location_id","customer_id"]
isOneToOne: false
      referencedRelation: "locations"
      referencedColumns: ["id","customer_id"]
    }
                  ]
                }
          }
          Functions: {
            "admin_cancel_task":
{ Args: { "p_reason": string,"p_task_id": string }; Returns: undefined
                           },
"admin_retry_communication":
{ Args: { "p_id": string }; Returns: boolean
                           },
"admin_save_task":
{ Args: { "p_assign": boolean,"p_products": Json,"p_task": Json,"p_task_id"?: string }; Returns: string
                           },
"agent_add_task_proof":
{ Args: { "p_description"?: string,"p_file_name": string,"p_path": string,"p_proof_type": string,"p_sha256": string,"p_task_id": string }; Returns: string
                           },
"agent_check_in":
{ Args: { "p_accuracy": number,"p_captured_at": string,"p_device_id"?: string,"p_latitude": number,"p_longitude": number,"p_notes"?: string,"p_task_id": string }; Returns: Json
                           },
"agent_complete_task":
{ Args: { "p_cash"?: Json,"p_lines"?: Json,"p_notes"?: string,"p_partial"?: boolean,"p_reason"?: string,"p_task_id": string }; Returns: Json
                           },
"agent_record_location":
{ Args: { "p_accuracy": number,"p_captured_at": string,"p_latitude": number,"p_longitude": number,"p_task_id": string }; Returns: Json
                           },
"agent_transition_task":
{ Args: { "p_expected_status": Database["public"]['Enums']["task_status"],"p_notes"?: string,"p_reason"?: string,"p_task_id": string,"p_to_status": Database["public"]['Enums']["task_status"] }; Returns: Database["public"]['Enums']["task_status"]
                           },
"ai_agent_workload":
{ Args: { "p_tz"?: string }; Returns: {
              "active_tasks": number,"agent_id": string,"agent_name": string,"due_today": number,"in_field": number,"overdue": number
            }[]
                           },
"ai_begin_run":
{ Args: { "p_kind": string,"p_min_interval_seconds"?: number,"p_trigger": string }; Returns: string
                           },
"ai_caller_allowed":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"ai_detect_anomalies":
{ Args: { "p_tz"?: string }; Returns: {
              "baseline": number,"dedupe_key": string,"detail": string,"entity_id": string,"entity_label": string,"entity_type": string,"kind": string,"observed": number,"severity": string,"title": string,"unit": string
            }[]
                           },
"ai_feature_enabled":
{ Args: { "p_key": string }; Returns: boolean
                           },
"ai_finish_run":
{ Args: { "p_error"?: string,"p_input_tokens"?: number,"p_insufficient"?: number,"p_model"?: string,"p_output_tokens"?: number,"p_predictions"?: number,"p_provider"?: string,"p_recommendations"?: number,"p_run": string,"p_status": string }; Returns: undefined
                           },
"ai_record_outcomes":
{ Args: { "p_tz"?: string }; Returns: number
                           },
"ai_review_recommendation":
{ Args: { "p_decision": string,"p_id": string,"p_notes"?: string }; Returns: string
                           },
"ai_set_setting":
{ Args: { "p_enabled": boolean,"p_key": string }; Returns: boolean
                           },
"ai_store_predictions":
{ Args: { "p_items": Json }; Returns: number
                           },
"ai_store_recommendations":
{ Args: { "p_items": Json }; Returns: number
                           },
"ai_store_summary":
{ Args: { "p_content": Json,"p_facts": Json,"p_model"?: string,"p_period": string,"p_provider": string }; Returns: string
                           },
"ai_submit_feedback":
{ Args: { "p_notes"?: string,"p_prediction_id": string,"p_rating": string }; Returns: string
                           },
"ai_task_features":
{ Args: { "p_tz"?: string }; Returns: {
              "agent_id": string,"agent_name": string,"all_closed": number,"all_failed": number,"baseline_scope": string,"checkin_ok": boolean,"checkin_rejected": number,"customer_name": string,"due_at": string,"is_overdue": boolean,"line_count": number,"location_closed": number,"location_failed": number,"location_id": string,"location_name": string,"minutes_in_stage": number,"minutes_to_due": number,"priority": number,"remaining_median_minutes": number,"remaining_p25_minutes": number,"remaining_p75_minutes": number,"remaining_samples": number,"stage_entered_at": string,"status": Database["public"]['Enums']["task_status"],"task_code": string,"task_id": string,"task_type": Database["public"]['Enums']["task_type"],"title": string,"type_closed": number,"type_failed": number,"type_late": number,"type_scheduled_completed": number
            }[]
                           },
"ai_volume_history":
{ Args: { "p_tz"?: string }; Returns: Json
                           },
"app_setting":
{ Args: { "p_default": number,"p_key": string }; Returns: number
                           },
"can_read_task_proof":
{ Args: { "p_name": string }; Returns: boolean
                           },
"can_upload_task_proof":
{ Args: { "p_name": string }; Returns: boolean
                           },
"claim_communications":
{ Args: { "p_limit"?: number }; Returns: {
              "attempt_count": number,
"channel": string,
"created_at": string,
"failed_at": string | null,
"id": string,
"last_error": string | null,
"message": string,
"notification_id": string | null,
"payload": NonNullable<Json>,
"provider": string | null,
"provider_message_id": string | null,
"recipient_address": string,
"recipient_user_id": string | null,
"scheduled_at": string,
"sent_at": string | null,
"status": string,
"subject": string | null,
"updated_at": string
            }[]
                          SetofOptions: {
        from: "*"
        to: "communication_queue"
        isOneToOne: false
        isSetofReturn: true
      } },
"complete_communication":
{ Args: { "p_error"?: string,"p_id": string,"p_outcome": string,"p_provider"?: string,"p_provider_message_id"?: string }; Returns: string
                           },
"current_agent_id":
{ Args: Record<PropertyKey, never>; Returns: string
                           },
"enqueue_task_reminders":
{ Args: { "p_time_zone"?: string }; Returns: number
                           },
"generate_task_code":
{ Args: Record<PropertyKey, never>; Returns: string
                           },
"get_my_role":
{ Args: Record<PropertyKey, never>; Returns: Database["public"]['Enums']["user_role"]
                           },
"haversine_meters":
{ Args: { "lat1": number,"lat2": number,"lng1": number,"lng2": number }; Returns: number
                           },
"is_admin":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"is_agent":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"is_my_task":
{ Args: { "p_task_id": string }; Returns: boolean
                           },
"mark_all_notifications_read":
{ Args: Record<PropertyKey, never>; Returns: number
                           },
"mark_notification_read":
{ Args: { "p_id": string }; Returns: boolean
                           },
"my_task_summary":
{ Args: { "p_from": string,"p_to": string,"p_tz"?: string }; Returns: Json
                           },
"notification_category":
{ Args: { "p_type": string }; Returns: string
                           },
"notification_task_data":
{ Args: { "p_link"?: boolean,"p_recipient": string,"p_task_id": string }; Returns: Json
                           },
"notify_admins":
{ Args: { "p_dedupe": string,"p_except"?: string,"p_message": string,"p_task_id": string,"p_title": string,"p_type": string }; Returns: number
                           },
"proof_path_task_id":
{ Args: { "p_name": string }; Returns: string
                           },
"publish_notification":
{ Args: { "p_dedupe": string,"p_link"?: boolean,"p_message": string,"p_recipient": string,"p_task_id": string,"p_title": string,"p_type": string }; Returns: string
                           },
"report_agents":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "accept_samples": number,"accepted": number,"active": number,"agent_id": string,"agent_name": string,"assigned": number,"avg_accept_seconds": number,"avg_checkin_seconds": number,"avg_execution_seconds": number,"avg_start_seconds": number,"cancelled": number,"cash_collected": number,"cash_expected": number,"checkin_samples": number,"checkins_ok": number,"checkins_rejected": number,"completed": number,"deliveries_closed": number,"employee_code": string,"execution_samples": number,"failed": number,"late": number,"median_execution_seconds": number,"on_time": number,"overdue": number,"partial": number,"qty_assigned": number,"qty_delivered": number,"start_samples": number,"started": number
            }[]
                           },
"report_cash":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: Json
                           },
"report_checkins":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: Json
                           },
"report_customers":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "active": number,"cancelled": number,"cash_collected": number,"cash_expected": number,"completed": number,"customer_id": string,"customer_name": string,"failed": number,"locations": number,"partial": number,"qty_assigned": number,"qty_delivered": number,"tasks": number
            }[]
                           },
"report_data_quality":
{ Args: { "p_from": string,"p_to": string,"p_tz"?: string }; Returns: {
              "detail": string,"issue": string,"severity": string,"task_code": string,"task_id": string
            }[]
                           },
"report_durations":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "avg_seconds": number,"max_seconds": number,"median_seconds": number,"min_seconds": number,"samples": number,"stage": string,"stage_order": number
            }[]
                           },
"report_locations":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "active": number,"avg_execution_seconds": number,"checkin_attempts": number,"checkins_ok": number,"checkins_rejected": number,"completed": number,"customer_id": string,"customer_name": string,"deliveries_closed": number,"deliveries_partial": number,"execution_samples": number,"failed": number,"location_city": string,"location_id": string,"location_name": string,"partial": number,"tasks": number
            }[]
                           },
"report_overview":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: Json
                           },
"report_products":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "assigned_qty": number,"delivered_qty": number,"outstanding_qty": number,"partial_lines": number,"product_id": string,"product_name": string,"sku": string,"tasks": number,"unit": string
            }[]
                           },
"report_task_facts":
{ Args: { "p_agent"?: string,"p_customer"?: string,"p_from": string,"p_location"?: string,"p_priority"?: number,"p_status"?: Database["public"]['Enums']["task_status"],"p_to": string,"p_type"?: Database["public"]['Enums']["task_type"],"p_tz"?: string }; Returns: {
              "accept_seconds": number,"accepted_at": string,"agent_id": string,"agent_name": string,"arrived_at": string,"assigned_at": string,"assigned_qty": number,"cash_outcome": string,"checked_in_at": string,"checkin_accuracy_m": number,"checkin_attempts": number,"checkin_distance_m": number,"checkin_ok": boolean,"checkin_rejected": number,"checkin_seconds": number,"collected_amount": number,"completed_at": string,"created_at": string,"customer_id": string,"customer_name": string,"delivered_qty": number,"delivery_outcome": string,"depart_seconds": number,"due_at": string,"employee_code": string,"execution_seconds": number,"expected_amount": number,"id": string,"is_active": boolean,"is_cancelled": boolean,"is_closed": boolean,"is_completed": boolean,"is_eligible": boolean,"is_failed": boolean,"is_overdue": boolean,"is_partial": boolean,"line_count": number,"location_city": string,"location_id": string,"location_name": string,"missing_proof": boolean,"needs_verification": boolean,"on_the_way_at": string,"on_time": boolean,"outstanding_amount": number,"payment_method": string,"priority": number,"proof_count": number,"scheduled_date": string,"scheduled_end_time": string,"scheduled_start_time": string,"start_seconds": number,"started_at": string,"status": Database["public"]['Enums']["task_status"],"task_code": string,"task_date": string,"task_type": Database["public"]['Enums']["task_type"],"title": string,"travel_seconds": number
            }[]
                           },
"task_status_counts":
{ Args: { "p_date": string }; Returns: {
              "status": Database["public"]['Enums']["task_status"],"total": number
            }[]
                           }
          }
          Enums: {
            "task_status": "DRAFT"|"ASSIGNED"|"ACCEPTED"|"ON_THE_WAY"|"ARRIVED"|"CHECKED_IN"|"IN_PROGRESS"|"COMPLETED"|"PARTIALLY_COMPLETED"|"FAILED"|"CANCELLED"|"RESCHEDULED"|"VERIFIED","task_type": "COLLECT_CASH"|"DELIVER_PRODUCTS"|"PICKUP"|"VERIFICATION"|"INSPECTION"|"DOCUMENT_COLLECTION"|"REPLACEMENT"|"SURVEY"|"OTHER","user_role": "ADMIN"|"AGENT"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "task_status": ["DRAFT", "ASSIGNED", "ACCEPTED", "ON_THE_WAY", "ARRIVED", "CHECKED_IN", "IN_PROGRESS", "COMPLETED", "PARTIALLY_COMPLETED", "FAILED", "CANCELLED", "RESCHEDULED", "VERIFIED"],"task_type": ["COLLECT_CASH", "DELIVER_PRODUCTS", "PICKUP", "VERIFICATION", "INSPECTION", "DOCUMENT_COLLECTION", "REPLACEMENT", "SURVEY", "OTHER"],"user_role": ["ADMIN", "AGENT"]
          }
        }
} as const
