-- Phase 8: task execution — delivery, cash collection and proof.
--
-- Idempotent and non-destructive. Reuses the Phase 3 tables (task_products,
-- cash_collections, task_proofs). Adds:
--   * tasks.expected_amount (set by admins for cash tasks), task_products.delivery_notes,
--     task_proofs.sha256; one cash collection per task; collected ≤ expected;
--   * private Storage bucket `task-proofs` with path-scoped storage policies;
--   * agent_complete_task() — saves execution data and decides COMPLETED vs
--     PARTIALLY_COMPLETED server-side (the only way to finish a task);
--   * agent_add_task_proof() — registers an uploaded file after server checks;
--   * agent_transition_task() no longer completes tasks (start/fail only);
--   * audit actions for execution steps.

begin;

-- ===========================================================================
-- 1. Columns & constraints
-- ===========================================================================
alter table public.tasks add column if not exists expected_amount numeric(14, 2);
alter table public.task_products add column if not exists delivery_notes text;
alter table public.task_proofs add column if not exists sha256 text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tasks_expected_amount_positive') then
    alter table public.tasks add constraint tasks_expected_amount_positive check (expected_amount > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'task_products_delivery_notes_length') then
    alter table public.task_products add constraint task_products_delivery_notes_length
      check (char_length(delivery_notes) <= 500);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cash_collections_not_over_expected') then
    alter table public.cash_collections add constraint cash_collections_not_over_expected
      check (collected_amount <= expected_amount);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'task_proofs_sha256_format') then
    alter table public.task_proofs add constraint task_proofs_sha256_format check (sha256 ~ '^[0-9a-f]{64}$');
  end if;
end
$$;

-- One collection record per task (corrections are admin updates, audited).
create unique index if not exists cash_collections_one_per_task on public.cash_collections (task_id);
-- The same file can't be attached twice to a task.
create unique index if not exists task_proofs_task_sha256 on public.task_proofs (task_id, sha256) where sha256 is not null;

-- Admins set the expected amount through admin_save_task (column grant for the update path).
grant update (expected_amount) on public.tasks to authenticated;

insert into public.app_settings (key, value, description) values
  ('proof_max_file_bytes', 10485760, 'Largest proof file accepted (bytes). Keep in sync with the task-proofs bucket limit.')
on conflict (key) do nothing;

-- ===========================================================================
-- 2. Storage: private bucket + path-scoped policies
-- ===========================================================================
-- Object names: tasks/{task_id}/proofs/{uuid}.{jpg|png|webp|pdf} — generated by the server.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('task-proofs', 'task-proofs', false, 10485760,
        array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Task id from a well-formed proof path, or NULL.
create or replace function public.proof_path_task_id(p_name text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select (regexp_match(p_name,
    '^tasks/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/proofs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp|pdf)$'))[1]::uuid
$$;

-- Agents may upload only into their own task's folder while it is being worked on.
create or replace function public.can_upload_task_proof(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.tasks t
    where t.id = public.proof_path_task_id(p_name)
      and t.agent_id = public.current_agent_id()
      and t.status in ('CHECKED_IN', 'IN_PROGRESS')
  )
$$;

-- Admins read all proofs; agents read proofs of their own (released) tasks.
create or replace function public.can_read_task_proof(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin() or public.is_my_task(public.proof_path_task_id(p_name))
$$;

revoke execute on function public.can_upload_task_proof(text), public.can_read_task_proof(text) from public, anon;
grant execute on function public.can_upload_task_proof(text), public.can_read_task_proof(text) to authenticated;

drop policy if exists "Agents upload proofs to own active tasks" on storage.objects;
create policy "Agents upload proofs to own active tasks" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'task-proofs' and public.can_upload_task_proof(name));

drop policy if exists "Read proofs of own tasks or as admin" on storage.objects;
create policy "Read proofs of own tasks or as admin" on storage.objects
  for select to authenticated
  using (bucket_id = 'task-proofs' and public.can_read_task_proof(name));
-- No update/delete policies: uploaded proof is immutable for users.

-- ===========================================================================
-- 3. Admin task save: expected amount for cash tasks
-- ===========================================================================
create or replace function public.admin_save_task(
  p_task     jsonb,
  p_products jsonb,
  p_assign   boolean,
  p_task_id  uuid default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing    public.tasks%rowtype;
  v_is_new      boolean := p_task_id is null;
  v_type        public.task_type := (p_task ->> 'task_type')::public.task_type;
  v_customer    uuid := (p_task ->> 'customer_id')::uuid;
  v_location    uuid := (p_task ->> 'location_id')::uuid;
  v_agent       uuid := nullif(p_task ->> 'agent_id', '')::uuid;
  v_status      public.task_status;
  v_assigned_at timestamptz;
  v_task_id     uuid;
  v_loc         record;
  v_line        jsonb;
  v_product     record;
  v_product_ids uuid[] := '{}';
  v_qty         numeric;
  v_price       numeric;
  v_expected    numeric;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'NOT_ADMIN';
  end if;

  if not v_is_new then
    select * into v_existing from public.tasks where id = p_task_id for update;
    if not found then
      raise exception using errcode = 'P0001', message = 'TASK_NOT_FOUND';
    end if;
    if v_existing.status not in ('DRAFT', 'ASSIGNED') then
      raise exception using errcode = 'P0001', message = 'TASK_NOT_EDITABLE';
    end if;
  end if;

  -- Status transition: create → DRAFT/ASSIGNED; DRAFT → DRAFT/ASSIGNED;
  -- ASSIGNED stays ASSIGNED (un-assigning is not supported; cancel instead).
  v_status := case
    when not v_is_new and v_existing.status = 'ASSIGNED' then 'ASSIGNED'
    when p_assign then 'ASSIGNED'
    else 'DRAFT'
  end;

  -- Customer
  if not exists (select 1 from public.customers where id = v_customer) then
    raise exception using errcode = 'P0001', message = 'CUSTOMER_NOT_FOUND';
  end if;
  if (v_is_new or v_customer is distinct from v_existing.customer_id)
     and not exists (select 1 from public.customers where id = v_customer and is_active) then
    raise exception using errcode = 'P0001', message = 'CUSTOMER_INACTIVE';
  end if;

  -- Location: must exist, belong to the customer, and be active if newly linked.
  select customer_id, is_active into v_loc from public.locations where id = v_location;
  if not found then
    raise exception using errcode = 'P0001', message = 'LOCATION_NOT_FOUND';
  end if;
  if v_loc.customer_id <> v_customer then
    raise exception using errcode = 'P0001', message = 'LOCATION_CUSTOMER_MISMATCH';
  end if;
  if (v_is_new or v_location is distinct from v_existing.location_id) and not v_loc.is_active then
    raise exception using errcode = 'P0001', message = 'LOCATION_INACTIVE';
  end if;

  -- Agent
  if v_status = 'ASSIGNED' and v_agent is null then
    raise exception using errcode = 'P0001', message = 'AGENT_REQUIRED';
  end if;
  if v_agent is not null then
    if not exists (select 1 from public.agents where id = v_agent) then
      raise exception using errcode = 'P0001', message = 'AGENT_NOT_FOUND';
    end if;
    if (v_is_new or v_agent is distinct from v_existing.agent_id
        or (v_status = 'ASSIGNED' and v_existing.status = 'DRAFT'))
       and not exists (
         select 1 from public.agents a join public.profiles p on p.id = a.profile_id
         where a.id = v_agent and a.is_active and p.is_active and p.role = 'AGENT'
       ) then
      raise exception using errcode = 'P0001', message = 'AGENT_INACTIVE';
    end if;
  end if;

  -- assigned_at: set when the task becomes ASSIGNED or is handed to another agent.
  v_assigned_at := case
    when v_status <> 'ASSIGNED' then null
    when v_is_new or v_existing.status = 'DRAFT' then now()
    when v_agent is distinct from v_existing.agent_id then now()
    else v_existing.assigned_at
  end;

  -- Product lines: validate everything before writing anything.
  if jsonb_typeof(coalesce(p_products, '[]'::jsonb)) <> 'array' then
    raise exception using errcode = 'P0001', message = 'PRODUCTS_INVALID';
  end if;
  for v_line in select * from jsonb_array_elements(coalesce(p_products, '[]'::jsonb)) loop
    select id, is_active, price into v_product
      from public.products where id = (v_line ->> 'product_id')::uuid;
    if not found then
      raise exception using errcode = 'P0001', message = 'PRODUCT_NOT_FOUND';
    end if;
    if v_product.id = any(v_product_ids) then
      raise exception using errcode = 'P0001', message = 'PRODUCT_DUPLICATE';
    end if;
    -- An inactive product may stay on a task it is already on, but not be added.
    if not v_product.is_active and (v_is_new or not exists (
         select 1 from public.task_products where task_id = p_task_id and product_id = v_product.id)) then
      raise exception using errcode = 'P0001', message = 'PRODUCT_INACTIVE';
    end if;
    v_qty := (v_line ->> 'assigned_quantity')::numeric;
    if v_qty is null or v_qty <= 0 then
      raise exception using errcode = 'P0001', message = 'QUANTITY_INVALID';
    end if;
    v_price := (v_line ->> 'unit_price')::numeric;
    if v_price is not null and v_price < 0 then
      raise exception using errcode = 'P0001', message = 'PRICE_INVALID';
    end if;
    v_product_ids := v_product_ids || v_product.id;
  end loop;

  if v_status = 'ASSIGNED' and v_type = 'DELIVER_PRODUCTS' and cardinality(v_product_ids) = 0 then
    raise exception using errcode = 'P0001', message = 'PRODUCTS_REQUIRED';
  end if;

  -- Expected amount: cash-collection tasks only (ignored for other types).
  if v_type = 'COLLECT_CASH' then
    v_expected := nullif(p_task ->> 'expected_amount', '')::numeric;
    if v_expected is not null and (v_expected <= 0 or v_expected > 999999999999.99 or v_expected <> round(v_expected, 2)) then
      raise exception using errcode = 'P0001', message = 'AMOUNT_INVALID';
    end if;
    if v_status = 'ASSIGNED' and v_expected is null then
      raise exception using errcode = 'P0001', message = 'EXPECTED_AMOUNT_REQUIRED';
    end if;
  end if;

  -- Write the task. created_by defaults to auth.uid(); task_code to the sequence.
  if v_is_new then
    insert into public.tasks (
      task_type, status, agent_id, customer_id, location_id, title, description, priority,
      scheduled_date, scheduled_start_time, scheduled_end_time, assigned_at, expected_amount
    ) values (
      v_type, v_status, v_agent, v_customer, v_location,
      p_task ->> 'title', nullif(p_task ->> 'description', ''), (p_task ->> 'priority')::integer,
      nullif(p_task ->> 'scheduled_date', '')::date,
      nullif(p_task ->> 'scheduled_start_time', '')::time,
      nullif(p_task ->> 'scheduled_end_time', '')::time,
      v_assigned_at, v_expected
    )
    returning id into v_task_id;
  else
    v_task_id := p_task_id;
    update public.tasks set
      task_type            = v_type,
      status               = v_status,
      agent_id             = v_agent,
      customer_id          = v_customer,
      location_id          = v_location,
      title                = p_task ->> 'title',
      description          = nullif(p_task ->> 'description', ''),
      priority             = (p_task ->> 'priority')::integer,
      scheduled_date       = nullif(p_task ->> 'scheduled_date', '')::date,
      scheduled_start_time = nullif(p_task ->> 'scheduled_start_time', '')::time,
      scheduled_end_time   = nullif(p_task ->> 'scheduled_end_time', '')::time,
      assigned_at          = v_assigned_at,
      expected_amount      = v_expected
    where id = v_task_id;
  end if;

  -- Planned lines (no execution data exists while DRAFT/ASSIGNED): remove
  -- lines no longer listed, then add new ones / update changed ones.
  delete from public.task_products
   where task_id = v_task_id and not (product_id = any(v_product_ids));

  insert into public.task_products (task_id, product_id, assigned_quantity, unit_price, notes)
  select v_task_id,
         p.id,
         (l ->> 'assigned_quantity')::numeric,
         coalesce((l ->> 'unit_price')::numeric, p.price),
         nullif(l ->> 'notes', '')
    from jsonb_array_elements(coalesce(p_products, '[]'::jsonb)) l
    join public.products p on p.id = (l ->> 'product_id')::uuid
  on conflict (task_id, product_id) do update set
    assigned_quantity = excluded.assigned_quantity,
    unit_price        = excluded.unit_price,
    notes             = excluded.notes
  where (task_products.assigned_quantity, task_products.unit_price, task_products.notes)
        is distinct from (excluded.assigned_quantity, excluded.unit_price, excluded.notes);

  return v_task_id;
end;
$$;

revoke execute on function public.admin_save_task(jsonb, jsonb, boolean, uuid) from public, anon;
grant execute on function public.admin_save_task(jsonb, jsonb, boolean, uuid) to authenticated;

-- ===========================================================================
-- 4. Generic agent transitions no longer complete tasks
-- ===========================================================================
-- Allowed (agent, own task only):
--   ASSIGNED   → ACCEPTED                     (accepted_at)
--   ACCEPTED   → ON_THE_WAY
--   ON_THE_WAY → ARRIVED                      (self-declared; NOT a verified visit)
--   CHECKED_IN → IN_PROGRESS                  (started_at)   — CHECKED_IN is set only by GPS check-in
--   ACCEPTED / ON_THE_WAY / ARRIVED / CHECKED_IN / IN_PROGRESS → FAILED (reason required)
--
-- Completion (COMPLETED / PARTIALLY_COMPLETED) is NOT a plain transition: it
-- goes through agent_complete_task(), which validates execution data first.
--
-- p_expected_status must equal the current status (optimistic concurrency):
-- a stale screen can never overwrite a newer state (e.g. an admin cancellation).
-- SECURITY DEFINER because agents have no direct UPDATE on tasks; ownership is
-- checked explicitly against current_agent_id() (active agent + profile only).
create or replace function public.agent_transition_task(
  p_task_id         uuid,
  p_expected_status public.task_status,
  p_to_status       public.task_status,
  p_reason          text default null,
  p_notes           text default null
)
returns public.task_status
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agent  uuid := public.current_agent_id();
  v_task   public.tasks%rowtype;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_notes  text := nullif(btrim(coalesce(p_notes, '')), '');
begin
  if v_agent is null then
    raise exception using errcode = '42501', message = 'NOT_AGENT';
  end if;

  select * into v_task from public.tasks where id = p_task_id for update;
  -- Someone else's task (or an unreleased draft) is reported as not found.
  if not found or v_task.agent_id is distinct from v_agent or v_task.status = 'DRAFT' then
    raise exception using errcode = 'P0001', message = 'TASK_NOT_FOUND';
  end if;

  if v_task.status <> p_expected_status then
    raise exception using errcode = 'P0001', message = 'STATUS_CHANGED';
  end if;

  if p_to_status = 'CHECKED_IN' then
    raise exception using errcode = 'P0001', message = 'CHECK_IN_REQUIRED';
  end if;

  if not (
       (v_task.status = 'ASSIGNED'    and p_to_status = 'ACCEPTED')
    or (v_task.status = 'ACCEPTED'    and p_to_status = 'ON_THE_WAY')
    or (v_task.status = 'ON_THE_WAY'  and p_to_status = 'ARRIVED')
    or (v_task.status = 'CHECKED_IN'  and p_to_status = 'IN_PROGRESS')
    or (v_task.status in ('ACCEPTED', 'ON_THE_WAY', 'ARRIVED', 'CHECKED_IN', 'IN_PROGRESS')
        and p_to_status = 'FAILED')
  ) then
    raise exception using errcode = 'P0001', message = 'TRANSITION_NOT_ALLOWED';
  end if;

  if p_to_status = 'FAILED'
     and (v_reason is null or char_length(v_reason) < 3) then
    raise exception using errcode = 'P0001', message = 'REASON_REQUIRED';
  end if;
  if char_length(coalesce(v_reason, '')) > 500 or char_length(coalesce(v_notes, '')) > 2000 then
    raise exception using errcode = 'P0001', message = 'TEXT_TOO_LONG';
  end if;

  perform set_config('app.status_change_reason', coalesce(v_reason, ''), true);
  perform set_config('app.status_change_notes', coalesce(v_notes, ''), true);

  update public.tasks set
    status           = p_to_status,
    accepted_at      = case when p_to_status = 'ACCEPTED' then now() else accepted_at end,
    started_at       = case when p_to_status = 'IN_PROGRESS' then now() else started_at end,
    failure_reason   = case when p_to_status = 'FAILED'
                            then v_reason || coalesce(' — ' || v_notes, '') else failure_reason end
  where id = p_task_id;

  -- Don't leak reason/notes into later statements of the same transaction.
  perform set_config('app.status_change_reason', '', true);
  perform set_config('app.status_change_notes', '', true);

  return p_to_status;
end;
$$;

revoke execute on function public.agent_transition_task(uuid, public.task_status, public.task_status, text, text)
  from public, anon;
grant execute on function public.agent_transition_task(uuid, public.task_status, public.task_status, text, text)
  to authenticated;

-- ===========================================================================
-- 5. agent_complete_task()
-- ===========================================================================
-- Finishes an IN_PROGRESS task of the calling agent. Execution data is saved
-- and the outcome decided here, in one transaction:
--   DELIVER_PRODUCTS  p_lines = [{task_product_id, delivered_quantity, notes}] for EVERY line.
--                     All full → COMPLETED; any shortfall → PARTIALLY_COMPLETED (reason required);
--                     nothing delivered → rejected (report a failure instead). ≥ 1 photo required.
--   COLLECT_CASH      p_cash = {collected_amount, payment_method, reference, notes}.
--                     = expected → COMPLETED; < expected → PARTIALLY_COMPLETED (reason required);
--                     > expected → rejected; 0 → rejected (report a failure instead).
--   DOCUMENT_COLLECTION  ≥ 1 proof required.
--   VERIFICATION / INSPECTION / SURVEY  result notes required.
--   Other types       notes optional; p_partial + reason → PARTIALLY_COMPLETED.
-- p_partial is ignored for delivery and cash: their outcome follows the data.
create or replace function public.agent_complete_task(
  p_task_id uuid,
  p_lines   jsonb   default null,
  p_cash    jsonb   default null,
  p_notes   text    default null,
  p_reason  text    default null,
  p_partial boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agent     uuid := public.current_agent_id();
  v_task      public.tasks%rowtype;
  v_notes     text := nullif(btrim(coalesce(p_notes, '')), '');
  v_reason    text := nullif(btrim(coalesce(p_reason, '')), '');
  v_status    public.task_status;
  v_summary   text;
  v_line      jsonb;
  v_tp        record;
  v_qty       numeric;
  v_lines     int;
  v_seen      uuid[] := '{}';
  v_shortfall boolean := false;
  v_total     numeric := 0;
  v_amount    numeric;
  v_method    text;
  v_reference text;
begin
  if v_agent is null then
    raise exception using errcode = '42501', message = 'UNAUTHORIZED';
  end if;

  select * into v_task from public.tasks where id = p_task_id for update;
  if not found or v_task.agent_id is distinct from v_agent or v_task.status = 'DRAFT' then
    raise exception using errcode = 'P0001', message = 'TASK_NOT_FOUND';
  end if;
  if v_task.status <> 'IN_PROGRESS' then
    raise exception using errcode = 'P0001', message = 'STATUS_CHANGED';
  end if;
  if char_length(coalesce(v_notes, '')) > 2000 or char_length(coalesce(v_reason, '')) > 500 then
    raise exception using errcode = 'P0001', message = 'TEXT_TOO_LONG';
  end if;

  if v_task.task_type = 'DELIVER_PRODUCTS' then
    -- ---------------------------------------------------------------- delivery
    select count(*) into v_lines from public.task_products where task_id = p_task_id;
    if v_lines = 0 then
      raise exception using errcode = 'P0001', message = 'NO_PRODUCT_LINES';
    end if;
    if jsonb_typeof(coalesce(p_lines, 'null'::jsonb)) <> 'array' or jsonb_array_length(p_lines) <> v_lines then
      raise exception using errcode = 'P0001', message = 'LINES_MISMATCH';
    end if;
    for v_line in select * from jsonb_array_elements(p_lines) loop
      select id, assigned_quantity into v_tp from public.task_products
       where id = (v_line ->> 'task_product_id')::uuid and task_id = p_task_id;
      if not found or v_tp.id = any(v_seen) then
        raise exception using errcode = 'P0001', message = 'LINES_MISMATCH';
      end if;
      v_seen := v_seen || v_tp.id;
      v_qty := (v_line ->> 'delivered_quantity')::numeric;
      if v_qty is null or v_qty < 0 or v_qty > v_tp.assigned_quantity or v_qty <> round(v_qty, 3) then
        raise exception using errcode = 'P0001', message = 'QUANTITY_INVALID';
      end if;
      if char_length(coalesce(v_line ->> 'notes', '')) > 500 then
        raise exception using errcode = 'P0001', message = 'TEXT_TOO_LONG';
      end if;
      update public.task_products
         set delivered_quantity = v_qty,
             delivery_notes = nullif(btrim(coalesce(v_line ->> 'notes', '')), '')
       where id = v_tp.id;
      v_total := v_total + v_qty;
      v_shortfall := v_shortfall or v_qty < v_tp.assigned_quantity;
    end loop;
    if v_total = 0 then
      raise exception using errcode = 'P0001', message = 'NOTHING_DELIVERED';
    end if;
    if not exists (select 1 from public.task_proofs where task_id = p_task_id and proof_type = 'PHOTO') then
      raise exception using errcode = 'P0001', message = 'PROOF_REQUIRED';
    end if;
    v_status := case when v_shortfall then 'PARTIALLY_COMPLETED' else 'COMPLETED' end;
    v_summary := case when v_shortfall then 'Partial delivery' else 'Full delivery' end;

  elsif v_task.task_type = 'COLLECT_CASH' then
    -- ---------------------------------------------------------------- cash
    if v_task.expected_amount is null then
      raise exception using errcode = 'P0001', message = 'EXPECTED_AMOUNT_MISSING';
    end if;
    if exists (select 1 from public.cash_collections where task_id = p_task_id) then
      raise exception using errcode = 'P0001', message = 'COLLECTION_ALREADY_RECORDED';
    end if;
    v_amount := (p_cash ->> 'collected_amount')::numeric;
    v_method := p_cash ->> 'payment_method';
    v_reference := nullif(btrim(coalesce(p_cash ->> 'reference', '')), '');
    if v_amount is null or v_amount < 0 or v_amount <> round(v_amount, 2) then
      raise exception using errcode = 'P0001', message = 'AMOUNT_INVALID';
    end if;
    if v_amount = 0 then
      raise exception using errcode = 'P0001', message = 'NOTHING_COLLECTED';
    end if;
    if v_amount > v_task.expected_amount then
      raise exception using errcode = 'P0001', message = 'OVER_COLLECTION';
    end if;
    if v_method is null or v_method not in ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'CHEQUE', 'OTHER') then
      raise exception using errcode = 'P0001', message = 'INVALID_PAYMENT_METHOD';
    end if;
    if v_method in ('UPI', 'BANK_TRANSFER', 'CHEQUE') and v_reference is null then
      raise exception using errcode = 'P0001', message = 'REFERENCE_REQUIRED';
    end if;
    if v_reference is not null and (char_length(v_reference) > 64 or v_reference !~ '^[A-Za-z0-9][A-Za-z0-9 ._/:#-]*$') then
      raise exception using errcode = 'P0001', message = 'REFERENCE_INVALID';
    end if;
    -- Never store card numbers: a reference that is 12–19 digits is refused.
    if v_reference is not null and regexp_replace(v_reference, '[ -]', '', 'g') ~ '^[0-9]{12,19}$' then
      raise exception using errcode = 'P0001', message = 'SENSITIVE_REFERENCE';
    end if;
    if char_length(coalesce(p_cash ->> 'notes', '')) > 500 then
      raise exception using errcode = 'P0001', message = 'TEXT_TOO_LONG';
    end if;
    insert into public.cash_collections (
      task_id, agent_id, expected_amount, collected_amount, payment_method,
      collection_reference, collected_at, notes
    ) values (
      p_task_id, v_agent, v_task.expected_amount, v_amount, v_method,
      v_reference, now(), nullif(btrim(coalesce(p_cash ->> 'notes', '')), '')
    );
    v_shortfall := v_amount < v_task.expected_amount;
    v_status := case when v_shortfall then 'PARTIALLY_COMPLETED' else 'COMPLETED' end;
    v_summary := case when v_shortfall then 'Partial collection' else 'Full collection' end;

  else
    -- ---------------------------------------------------------------- other types
    if v_task.task_type = 'DOCUMENT_COLLECTION'
       and not exists (select 1 from public.task_proofs where task_id = p_task_id) then
      raise exception using errcode = 'P0001', message = 'PROOF_REQUIRED';
    end if;
    if v_task.task_type in ('VERIFICATION', 'INSPECTION', 'SURVEY') and v_notes is null then
      raise exception using errcode = 'P0001', message = 'RESULT_REQUIRED';
    end if;
    v_shortfall := coalesce(p_partial, false);
    v_status := case when v_shortfall then 'PARTIALLY_COMPLETED' else 'COMPLETED' end;
    v_summary := case when v_shortfall then 'Partially completed' else 'Completed' end;
  end if;

  if v_shortfall and (v_reason is null or char_length(v_reason) < 3) then
    raise exception using errcode = 'P0001', message = 'REASON_REQUIRED';
  end if;

  perform set_config('app.status_change_reason',
    v_summary || case when v_shortfall then ': ' || v_reason else '' end, true);
  perform set_config('app.status_change_notes', coalesce(v_notes, ''), true);
  update public.tasks set
    status = v_status,
    completed_at = now(),
    completion_notes = case
      when v_shortfall then v_reason || coalesce(' — ' || v_notes, '')
      else v_notes
    end
  where id = p_task_id;
  perform set_config('app.status_change_reason', '', true);
  perform set_config('app.status_change_notes', '', true);

  return jsonb_build_object('status', v_status, 'summary', v_summary);
end;
$$;

revoke execute on function public.agent_complete_task(uuid, jsonb, jsonb, text, text, boolean) from public, anon;
grant execute on function public.agent_complete_task(uuid, jsonb, jsonb, text, text, boolean) to authenticated;

-- ===========================================================================
-- 6. agent_add_task_proof()
-- ===========================================================================
-- Registers a file the agent uploaded through a server-issued signed URL.
-- Checks ownership, task state, the server-generated path, and the stored
-- object's real size and type; the app has already checked the file's bytes.
create or replace function public.agent_add_task_proof(
  p_task_id     uuid,
  p_path        text,
  p_proof_type  text,
  p_file_name   text,
  p_sha256      text,
  p_description text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agent uuid := public.current_agent_id();
  v_task  public.tasks%rowtype;
  v_obj   record;
  v_size  bigint;
  v_mime  text;
  v_id    uuid;
  v_max   numeric := public.app_setting('proof_max_file_bytes', 10485760);
begin
  if v_agent is null then
    raise exception using errcode = '42501', message = 'UNAUTHORIZED';
  end if;
  select * into v_task from public.tasks where id = p_task_id for update;
  if not found or v_task.agent_id is distinct from v_agent or v_task.status = 'DRAFT' then
    raise exception using errcode = 'P0001', message = 'TASK_NOT_FOUND';
  end if;
  if v_task.status not in ('CHECKED_IN', 'IN_PROGRESS') then
    raise exception using errcode = 'P0001', message = 'INVALID_TASK_STATUS';
  end if;
  if public.proof_path_task_id(p_path) is distinct from p_task_id then
    raise exception using errcode = 'P0001', message = 'INVALID_PATH';
  end if;
  if p_proof_type not in ('PHOTO', 'DOCUMENT') then
    raise exception using errcode = 'P0001', message = 'INVALID_PROOF_TYPE';
  end if;
  if p_sha256 is null or p_sha256 !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'INVALID_FILE';
  end if;
  if char_length(coalesce(p_file_name, '')) > 200 or char_length(coalesce(p_description, '')) > 500 then
    raise exception using errcode = 'P0001', message = 'TEXT_TOO_LONG';
  end if;

  select o.metadata into v_obj from storage.objects o where o.bucket_id = 'task-proofs' and o.name = p_path;
  if not found then
    raise exception using errcode = 'P0001', message = 'FILE_NOT_FOUND';
  end if;
  v_size := (v_obj.metadata ->> 'size')::bigint;
  v_mime := v_obj.metadata ->> 'mimetype';
  if v_size is null or v_size <= 0 or v_size > v_max then
    raise exception using errcode = 'P0001', message = 'FILE_TOO_LARGE';
  end if;
  if not (
       (p_proof_type = 'PHOTO' and v_mime in ('image/jpeg', 'image/png', 'image/webp'))
    or (p_proof_type = 'DOCUMENT' and v_mime in ('application/pdf', 'image/jpeg', 'image/png', 'image/webp'))
  -- (CASE is parenthesised: PL/pgSQL ends an IF condition at the first THEN.)
  ) or v_mime is distinct from (case substring(p_path from '\.([a-z]+)$')
                   when 'jpg' then 'image/jpeg' when 'png' then 'image/png'
                   when 'webp' then 'image/webp' when 'pdf' then 'application/pdf' end) then
    raise exception using errcode = 'P0001', message = 'INVALID_FILE_TYPE';
  end if;
  if exists (select 1 from public.task_proofs where task_id = p_task_id and sha256 = p_sha256) then
    raise exception using errcode = 'P0001', message = 'PROOF_DUPLICATE';
  end if;

  insert into public.task_proofs (task_id, agent_id, proof_type, storage_path, file_name, mime_type,
                                  file_size_bytes, description, sha256)
  values (p_task_id, v_agent, p_proof_type, p_path, nullif(btrim(coalesce(p_file_name, '')), ''), v_mime,
          v_size, nullif(btrim(coalesce(p_description, '')), ''), p_sha256)
  returning id into v_id;
  return v_id;
end;
$$;

revoke execute on function public.agent_add_task_proof(uuid, text, text, text, text, text) from public, anon;
grant execute on function public.agent_add_task_proof(uuid, text, text, text, text, text) to authenticated;

-- ===========================================================================
-- 7. Audit: execution actions
-- ===========================================================================
create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  entity    text := tg_argv[0];
  old_row   jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  new_row   jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  old_diff  jsonb;
  new_diff  jsonb;
  keys      text[];
  action    text;
begin
  if tg_op = 'UPDATE' then
    select jsonb_object_agg(n.key, old_row -> n.key), jsonb_object_agg(n.key, n.value)
      into old_diff, new_diff
      from jsonb_each(new_row) n
     where n.key <> 'updated_at' and n.value is distinct from old_row -> n.key;
    if new_diff is null then
      return null; -- no-op update
    end if;
    select array_agg(k order by k) into keys from jsonb_object_keys(new_diff) k;

    action := case
      when entity = 'TASK' and new_diff ? 'status' then
        case new_diff ->> 'status'
          when 'ASSIGNED'            then case when old_diff ->> 'status' = 'DRAFT' then 'ASSIGN_TASK' else 'UPDATE_TASK' end
          when 'ACCEPTED'            then 'ACCEPT_TASK'
          when 'ON_THE_WAY'          then 'START_TRAVEL'
          when 'ARRIVED'             then 'MARK_ARRIVED'
          when 'CHECKED_IN'          then 'TASK_CHECK_IN'
          when 'IN_PROGRESS'         then 'START_TASK'
          when 'COMPLETED'           then 'COMPLETE_TASK'
          when 'PARTIALLY_COMPLETED' then 'PARTIALLY_COMPLETE_TASK'
          when 'FAILED'              then 'REPORT_TASK_FAILURE'
          when 'CANCELLED'           then 'CANCEL_TASK'
          when 'VERIFIED'            then 'VERIFY_TASK'
          else 'UPDATE_TASK'
        end
      when entity = 'TASK' and new_diff ? 'agent_id' then 'REASSIGN_TASK'
      when entity = 'TASK'
           and keys <@ array['scheduled_date', 'scheduled_start_time', 'scheduled_end_time'] then 'RESCHEDULE_TASK'
      when entity = 'TASK_PRODUCT' and new_diff ? 'delivered_quantity' then 'UPDATE_DELIVERY_QUANTITY'
      when entity = 'TASK_PRODUCT' then 'UPDATE_TASK_PRODUCT'
      when entity = 'CASH_COLLECTION' then 'CORRECT_CASH_COLLECTION'
      when keys = array['is_active'] then
        case when (new_diff ->> 'is_active')::boolean then 'ACTIVATE_' else 'DEACTIVATE_' end || entity
      else 'UPDATE_' || entity
    end;
  else
    old_diff := old_row - 'updated_at';
    new_diff := new_row - 'updated_at';
    action := case
      when entity = 'TASK_PRODUCT' and tg_op = 'INSERT' then 'ADD_TASK_PRODUCT'
      when entity = 'TASK_PRODUCT' and tg_op = 'DELETE' then 'REMOVE_TASK_PRODUCT'
      when entity = 'CASH_COLLECTION' and tg_op = 'INSERT' then 'SUBMIT_CASH_COLLECTION'
      when entity = 'TASK_PROOF' and tg_op = 'INSERT' then 'UPLOAD_TASK_PROOF'
      when tg_op = 'INSERT' then 'CREATE_' || entity
      else 'DELETE_' || entity
    end;
  end if;

  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, old_values, new_values)
  values (auth.uid(), action, entity, (coalesce(new_row, old_row) ->> 'id')::uuid, old_diff, new_diff);
  return null;
end;
$$;

revoke execute on function public.audit_row_change() from public, anon, authenticated;

drop trigger if exists task_proofs_audit on public.task_proofs;
create trigger task_proofs_audit
  after insert or update or delete on public.task_proofs
  for each row execute function public.audit_row_change('TASK_PROOF');

commit;
